In [21]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import shap
import matplotlib.pyplot as plt

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a linear SVM model
linear_svm = SVC(kernel='linear', probability=True)
linear_svm.fit(X_train, y_train)

# Make predictions
y_pred = linear_svm.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the evaluation results
print(f'Accuracy: {accuracy}')
print('Classification Report:')
print(class_report)
print('Confusion Matrix:')
print(conf_matrix)

# Explain the model's predictions using SHAP
# Create a SHAP explainer for the linear SVM
explainer = shap.Explainer(linear_svm, X_train)

# Calculate SHAP values for the test set
shap_values = explainer(X_test)
print('=====')
shap_values

Accuracy: 1.0
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
=====

.values =
array([[[-1.53753727e-02, -2.12935953e-03,  1.88466130e-01],
        [-1.42769284e-01, -4.89566542e-02, -3.32962708e-01],
        [-1.01705873e+00, -5.46456665e-01, -2.06476880e+00],
        [-1.57800175e-02, -9.91396776e-03, -5.79124496e-02]],

       [[ 3.14917272e-03,  4.36133879e-04, -3.86014966e-02],
        [ 3.78286498e-01,  1.29717266e-01,  8.82229657e-01],
        [ 1.99199076e+00,  1.07027903e+00,  4.04401464e+00],
        [ 4.01926328e-01,  2.52514591e-01,  1.47506416e+00]],

       [[-8.94735543e-02, -1.23913331e-02,  1.09673664e+00],
        [-2.46980441e-01, -8.46914383e-02, -5.76001181e-01],
        [-3.22369502e+00, -1.73206284e+00, -6.54454333e+00],
        [-5.26309996e-01, -3.30659984e-01, -1.93155052e+00]],

       [[-1.07442363e-02, -1.48798617e-03,  1.31699224e-01],
        [-9.06637061e-02, -3.10892622e-02, -2.11443472e-01],
        [-8.16455429e-01, -4.38674286e-01, -1.65751657e+00],
        [-1.55015466e-01, -9.73901539e-02, -5.68904651e-01]],

       [[-4.77933271e-02, -6.61897298e-03,  5.85834478e-01],
        [-1.42769284e-01, -4.89566542e-02, -3.32962708e-01],
        [-1.11736038e+00, -6.00347855e-01, -2.26839492e+00],
        [-1.08603650e-01, -6.82314252e-02, -3.98573917e-01]],

       [[ 1.70425818e-02,  2.36025393e-03, -2.08902217e-01],
        [ 1.69864185e-01,  5.82476981e-02,  3.96152711e-01],
        [ 2.19259406e+00,  1.17806141e+00,  4.45126687e+00],
        [ 3.55514512e-01,  2.23355862e-01,  1.30473342e+00]],

       [[ 7.78030907e-03,  1.07750723e-03, -9.53684034e-02],
        [-9.06637061e-02, -3.10892622e-02, -2.11443472e-01],
        [ 8.62594188e-02,  4.63464233e-02,  1.75118459e-01],
        [-6.21918337e-02, -3.90726965e-02, -2.28243184e-01]],

       [[-5.24244635e-02, -7.26034633e-03,  6.42601385e-01],
        [ 1.35474503e-02,  4.64552193e-03,  3.15950015e-02],
        [-1.41826533e+00, -7.62021425e-01, -2.87927326e+00],
        [-5.26309996e-01, -3.30659984e-01, -1.93155052e+00]],

       [[-2.00065090e-02, -2.77073288e-03,  2.45233037e-01],
        [-4.55402753e-01, -1.56161007e-01, -1.06207813e+00],
        [-8.16455429e-01, -4.38674286e-01, -1.65751657e+00],
        [-1.55015466e-01, -9.73901539e-02, -5.68904651e-01]],

       [[-1.48196363e-03, -2.05239472e-04,  1.81654102e-02],
        [-1.94874862e-01, -6.68240463e-02, -4.54481945e-01],
        [-2.14645530e-01, -1.15327146e-01, -4.35759885e-01],
        [-1.57800175e-02, -9.91396776e-03, -5.79124496e-02]],

       [[-3.38999181e-02, -4.69485293e-03,  4.15533758e-01],
        [ 6.56530285e-02,  2.25129140e-02,  1.53114238e-01],
        [-1.41826533e+00, -7.62021425e-01, -2.87927326e+00],
        [-3.87074547e-01, -2.43183797e-01, -1.42055832e+00]],

       [[ 4.48293999e-02,  6.20849404e-03, -5.49503657e-01],
        [-3.85581279e-02, -1.32218701e-02, -8.99242351e-02],
        [ 2.29289571e+00,  1.23195260e+00,  4.65489298e+00],
        [ 4.94749961e-01,  3.10832048e-01,  1.81572562e+00]],

       [[ 1.24114454e-02,  1.71888058e-03, -1.52135310e-01],
        [ 2.21969763e-01,  7.61150902e-02,  5.17671948e-01],
        [ 2.39319736e+00,  1.28584379e+00,  4.85851910e+00],
        [ 4.48338145e-01,  2.81673319e-01,  1.64539489e+00]],

       [[ 4.01982635e-02,  5.56712069e-03, -4.92736751e-01],
        [ 1.35474503e-02,  4.64552193e-03,  3.15950015e-02],
        [ 2.19259406e+00,  1.17806141e+00,  4.45126687e+00],
        [ 4.94749961e-01,  3.10832048e-01,  1.81572562e+00]],

       [[ 3.09359908e-02,  4.28437398e-03, -3.79202937e-01],
        [ 3.78286498e-01,  1.29717266e-01,  8.82229657e-01],
        [ 2.19259406e+00,  1.17806141e+00,  4.45126687e+00],
        [ 4.01926328e-01,  2.52514591e-01,  1.47506416e+00]],

       [[-2.46376454e-02, -3.41210623e-03,  3.01999944e-01],
        [ 1.17758607e-01,  4.03803060e-02,  2.74633475e-01],
        [-1.01705873e+00, -5.46456665e-01, -2.06476880e+00],
        [-2.01427282e-01, -1.26548883e-01, -7.39235385e-01]],

       [[-3.38999181e-02, -4.69485293e-03,  4.15533758e-01],
        [-3.85581279e-02, -1.32218701e-02, -8.99242351e-02],
        [-2.12037688e+00, -1.13925975e+00, -4.30465606e+00],
        [-4.79898180e-01, -3.01501255e-01, -1.76121979e+00]],

       [[ 7.78030907e-03,  1.07750723e-03, -9.53684034e-02],
        [-2.99086019e-01, -1.02558830e-01, -6.97520418e-01],
        [-2.14645530e-01, -1.15327146e-01, -4.35759885e-01],
        [ 3.06317987e-02,  1.92447610e-02,  1.12418284e-01]],

       [[ 3.14917272e-03,  4.36133879e-04, -3.86014966e-02],
        [-1.42769284e-01, -4.89566542e-02, -3.32962708e-01],
        [-8.16455429e-01, -4.38674286e-01, -1.65751657e+00],
        [-6.21918337e-02, -3.90726965e-02, -2.28243184e-01]],

       [[-2.92687817e-02, -4.05347958e-03,  3.58766851e-01],
        [-1.42769284e-01, -4.89566542e-02, -3.32962708e-01],
        [-1.91977358e+00, -1.03147737e+00, -3.89740384e+00],
        [-4.79898180e-01, -3.01501255e-01, -1.76121979e+00]],

       [[ 4.94605362e-02,  6.84986739e-03, -6.06270564e-01],
        [ 6.56530285e-02,  2.25129140e-02,  1.53114238e-01],
        [ 2.09229241e+00,  1.12417022e+00,  4.24764075e+00],
        [ 4.48338145e-01,  2.81673319e-01,  1.64539489e+00]],

       [[-1.53753727e-02, -2.12935953e-03,  1.88466130e-01],
        [-3.85581279e-02, -1.32218701e-02, -8.99242351e-02],
        [-1.21766203e+00, -6.54239045e-01, -2.47202103e+00],
        [-2.94250915e-01, -1.84866340e-01, -1.07989685e+00]],

       [[ 3.55671272e-02,  4.92574734e-03, -4.35969844e-01],
        [ 1.69864185e-01,  5.82476981e-02,  3.96152711e-01],
        [ 2.09229241e+00,  1.12417022e+00,  4.24764075e+00],
        [ 3.55514512e-01,  2.23355862e-01,  1.30473342e+00]],

       [[-2.92687817e-02, -4.05347958e-03,  3.58766851e-01],
        [-1.42769284e-01, -4.89566542e-02, -3.32962708e-01],
        [-1.91977358e+00, -1.03147737e+00, -3.89740384e+00],
        [-4.33486363e-01, -2.72342526e-01, -1.59088906e+00]],

       [[-9.87358270e-02, -1.36740798e-02,  1.21027045e+00],
        [ 3.78286498e-01,  1.29717266e-01,  8.82229657e-01],
        [-2.72218677e+00, -1.46260689e+00, -5.52641275e+00],
        [-3.87074547e-01, -2.43183797e-01, -1.42055832e+00]],

       [[-4.31621908e-02, -5.97759963e-03,  5.29067571e-01],
        [-3.85581279e-02, -1.32218701e-02, -8.99242351e-02],
        [-1.51856698e+00, -8.15912615e-01, -3.08289938e+00],
        [-5.26309996e-01, -3.30659984e-01, -1.93155052e+00]],

       [[-4.31621908e-02, -5.97759963e-03,  5.29067571e-01],
        [-2.99086019e-01, -1.02558830e-01, -6.97520418e-01],
        [-2.12037688e+00, -1.13925975e+00, -4.30465606e+00],
        [-2.94250915e-01, -1.84866340e-01, -1.07989685e+00]],

       [[-4.77933271e-02, -6.61897298e-03,  5.85834478e-01],
        [ 6.56530285e-02,  2.25129140e-02,  1.53114238e-01],
        [-2.22067853e+00, -1.19315094e+00, -4.50828218e+00],
        [-5.26309996e-01, -3.30659984e-01, -1.93155052e+00]],

       [[ 4.48293999e-02,  6.20849404e-03, -5.49503657e-01],
        [-3.85581279e-02, -1.32218701e-02, -8.99242351e-02],
        [ 2.29289571e+00,  1.23195260e+00,  4.65489298e+00],
        [ 4.01926328e-01,  2.52514591e-01,  1.47506416e+00]],

       [[ 4.48293999e-02,  6.20849404e-03, -5.49503657e-01],
        [ 1.35474503e-02,  4.64552193e-03,  3.15950015e-02],
        [ 2.09229241e+00,  1.12417022e+00,  4.24764075e+00],
        [ 4.48338145e-01,  2.81673319e-01,  1.64539489e+00]]])

.base_values =
array([[-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067],
       [-1.45029637, -0.30879754,  3.32098067]])

.data =
array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2]])

In [28]:
import pandas as pd
# Explain the model's predictions using SHAP
# Create a SHAP explainer for the linear SVM
explainer = shap.Explainer(linear_svm, X_train)

# Calculate SHAP values for the test set
shap_values = explainer(X_test)

# Aggregate SHAP values to get feature importance for each class
# Extract the SHAP values for each class
shap_values_per_class = shap_values.values

# Compute the mean absolute SHAP values for each feature for each class
feature_importance = np.mean(np.abs(shap_values_per_class), axis=0)

# Create a DataFrame for better visualization
feature_importance_df = pd.DataFrame(feature_importance, columns=iris.target_names, index=iris.feature_names)

print("Feature importance for each class:")
feature_importance_df

Feature importance for each class:

                     setosa  versicolor  virginica
sepal length (cm)  0.032616    0.004517   0.399790
sepal width (cm)   0.154510    0.052983   0.360345
petal length (cm)  1.658722    0.891217   3.367433
petal width (cm)   0.330638    0.207727   1.213436

In [37]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
import shap
import pandas as pd

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Prepare for cross-validation
n_splits = 10
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize an array to store feature importances for each fold
feature_importance_per_fold = np.zeros((n_splits, len(iris.feature_names), len(iris.target_names)))

# Perform 5-fold cross-validation
for fold, (train_index, test_index) in enumerate(skf.split(X, y)):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Train a linear SVM model
    linear_svm = SVC(kernel='linear', probability=True)
    linear_svm.fit(X_train, y_train)

    # Explain the model's predictions using SHAP
    explainer = shap.Explainer(linear_svm, X_train)
    shap_values = explainer(X_test)

    # Aggregate SHAP values to get feature importance for each class
    shap_values_per_class = shap_values.values
    feature_importance = np.mean(np.abs(shap_values_per_class), axis=0)
    feature_importance_per_fold[fold] = feature_importance

# Calculate the mean and standard deviation of feature importance across all folds
average_feature_importance = np.mean(feature_importance_per_fold, axis=0)
std_feature_importance = np.std(feature_importance_per_fold, axis=0)

# Create DataFrames for better visualization
feature_importance_df = pd.DataFrame(average_feature_importance, columns=[f"{cls} mean" for cls in iris.target_names], index=iris.feature_names)
std_feature_importance_df = pd.DataFrame(std_feature_importance, columns=[f"{cls} std" for cls in iris.target_names], index=iris.feature_names)

# Concatenate the average feature importance and standard deviation DataFrames
combined_feature_importance_df = pd.concat([feature_importance_df, std_feature_importance_df], axis=1)
# Reorder the columns to ensure the correct order: avg std avg std
combined_feature_importance_df = combined_feature_importance_df[['setosa mean',
                                                                 'setosa std',
                                                                 'versicolor mean',
                                                                 'versicolor std',
                                                                 'virginica mean',
                                                                 'virginica std']]
combined_feature_importance_df['total mean'] = combined_feature_importance_df[['setosa mean', 'versicolor mean', 'virginica mean']].sum(axis=1)
print("Average feature importance and standard deviation for each class over 5 folds:")
combined_feature_importance_df

Average feature importance and standard deviation for each class over 5 folds:

,setosa mean,setosa std,versicolor mean,versicolor std,virginica mean,virginica std,total mean
sepal length (cm),0.045268,0.042555,0.026365,0.036567,0.413651,0.171848,0.485285
sepal width (cm),0.174740,0.042219,0.059006,0.011502,0.224847,0.092296,0.458593
petal length (cm),1.500168,0.090946,0.831894,0.064708,3.068750,0.272810,5.400812
petal width (cm),0.303388,0.033255,0.182132,0.018157,1.356861,0.096603,1.842381

In [32]:
shap_values_per_class

array([[[-1.53753727e-02, -2.12935953e-03,  1.88466130e-01],
        [-1.42769284e-01, -4.89566542e-02, -3.32962708e-01],
        [-1.01705873e+00, -5.46456665e-01, -2.06476880e+00],
        [-1.57800175e-02, -9.91396776e-03, -5.79124496e-02]],

       [[ 3.14917272e-03,  4.36133879e-04, -3.86014966e-02],
        [ 3.78286498e-01,  1.29717266e-01,  8.82229657e-01],
        [ 1.99199076e+00,  1.07027903e+00,  4.04401464e+00],
        [ 4.01926328e-01,  2.52514591e-01,  1.47506416e+00]],

       [[-8.94735543e-02, -1.23913331e-02,  1.09673664e+00],
        [-2.46980441e-01, -8.46914383e-02, -5.76001181e-01],
        [-3.22369502e+00, -1.73206284e+00, -6.54454333e+00],
        [-5.26309996e-01, -3.30659984e-01, -1.93155052e+00]],

       [[-1.07442363e-02, -1.48798617e-03,  1.31699224e-01],
        [-9.06637061e-02, -3.10892622e-02, -2.11443472e-01],
        [-8.16455429e-01, -4.38674286e-01, -1.65751657e+00],
        [-1.55015466e-01, -9.73901539e-02, -5.68904651e-01]],

       [[-4.77933271e-02, -6.61897298e-03,  5.85834478e-01],
        [-1.42769284e-01, -4.89566542e-02, -3.32962708e-01],
        [-1.11736038e+00, -6.00347855e-01, -2.26839492e+00],
        [-1.08603650e-01, -6.82314252e-02, -3.98573917e-01]],

       [[ 1.70425818e-02,  2.36025393e-03, -2.08902217e-01],
        [ 1.69864185e-01,  5.82476981e-02,  3.96152711e-01],
        [ 2.19259406e+00,  1.17806141e+00,  4.45126687e+00],
        [ 3.55514512e-01,  2.23355862e-01,  1.30473342e+00]],

       [[ 7.78030907e-03,  1.07750723e-03, -9.53684034e-02],
        [-9.06637061e-02, -3.10892622e-02, -2.11443472e-01],
        [ 8.62594188e-02,  4.63464233e-02,  1.75118459e-01],
        [-6.21918337e-02, -3.90726965e-02, -2.28243184e-01]],

       [[-5.24244635e-02, -7.26034633e-03,  6.42601385e-01],
        [ 1.35474503e-02,  4.64552193e-03,  3.15950015e-02],
        [-1.41826533e+00, -7.62021425e-01, -2.87927326e+00],
        [-5.26309996e-01, -3.30659984e-01, -1.93155052e+00]],

       [[-2.00065090e-02, -2.77073288e-03,  2.45233037e-01],
        [-4.55402753e-01, -1.56161007e-01, -1.06207813e+00],
        [-8.16455429e-01, -4.38674286e-01, -1.65751657e+00],
        [-1.55015466e-01, -9.73901539e-02, -5.68904651e-01]],

       [[-1.48196363e-03, -2.05239472e-04,  1.81654102e-02],
        [-1.94874862e-01, -6.68240463e-02, -4.54481945e-01],
        [-2.14645530e-01, -1.15327146e-01, -4.35759885e-01],
        [-1.57800175e-02, -9.91396776e-03, -5.79124496e-02]],

       [[-3.38999181e-02, -4.69485293e-03,  4.15533758e-01],
        [ 6.56530285e-02,  2.25129140e-02,  1.53114238e-01],
        [-1.41826533e+00, -7.62021425e-01, -2.87927326e+00],
        [-3.87074547e-01, -2.43183797e-01, -1.42055832e+00]],

       [[ 4.48293999e-02,  6.20849404e-03, -5.49503657e-01],
        [-3.85581279e-02, -1.32218701e-02, -8.99242351e-02],
        [ 2.29289571e+00,  1.23195260e+00,  4.65489298e+00],
        [ 4.94749961e-01,  3.10832048e-01,  1.81572562e+00]],

       [[ 1.24114454e-02,  1.71888058e-03, -1.52135310e-01],
        [ 2.21969763e-01,  7.61150902e-02,  5.17671948e-01],
        [ 2.39319736e+00,  1.28584379e+00,  4.85851910e+00],
        [ 4.48338145e-01,  2.81673319e-01,  1.64539489e+00]],

       [[ 4.01982635e-02,  5.56712069e-03, -4.92736751e-01],
        [ 1.35474503e-02,  4.64552193e-03,  3.15950015e-02],
        [ 2.19259406e+00,  1.17806141e+00,  4.45126687e+00],
        [ 4.94749961e-01,  3.10832048e-01,  1.81572562e+00]],

       [[ 3.09359908e-02,  4.28437398e-03, -3.79202937e-01],
        [ 3.78286498e-01,  1.29717266e-01,  8.82229657e-01],
        [ 2.19259406e+00,  1.17806141e+00,  4.45126687e+00],
        [ 4.01926328e-01,  2.52514591e-01,  1.47506416e+00]],

       [[-2.46376454e-02, -3.41210623e-03,  3.01999944e-01],
        [ 1.17758607e-01,  4.03803060e-02,  2.74633475e-01],
        [-1.01705873e+00, -5.46456665e-01, -2.06476880e+00],
        [-2.01427282e-01, -1.26548883e-01, -7.39235385e-01]],

       [[-3.38999181e-02, -4.69485293e-03,  4.15533758e-01],
        [-3.85581279e-02, -1.32218701e-02, -8.99242351e-02],
        [-2.12037688e+00, -1.13925975e+00, -4.30465606e+00],
        [-4.79898180e-01, -3.01501255e-01, -1.76121979e+00]],

       [[ 7.78030907e-03,  1.07750723e-03, -9.53684034e-02],
        [-2.99086019e-01, -1.02558830e-01, -6.97520418e-01],
        [-2.14645530e-01, -1.15327146e-01, -4.35759885e-01],
        [ 3.06317987e-02,  1.92447610e-02,  1.12418284e-01]],

       [[ 3.14917272e-03,  4.36133879e-04, -3.86014966e-02],
        [-1.42769284e-01, -4.89566542e-02, -3.32962708e-01],
        [-8.16455429e-01, -4.38674286e-01, -1.65751657e+00],
        [-6.21918337e-02, -3.90726965e-02, -2.28243184e-01]],

       [[-2.92687817e-02, -4.05347958e-03,  3.58766851e-01],
        [-1.42769284e-01, -4.89566542e-02, -3.32962708e-01],
        [-1.91977358e+00, -1.03147737e+00, -3.89740384e+00],
        [-4.79898180e-01, -3.01501255e-01, -1.76121979e+00]],

       [[ 4.94605362e-02,  6.84986739e-03, -6.06270564e-01],
        [ 6.56530285e-02,  2.25129140e-02,  1.53114238e-01],
        [ 2.09229241e+00,  1.12417022e+00,  4.24764075e+00],
        [ 4.48338145e-01,  2.81673319e-01,  1.64539489e+00]],

       [[-1.53753727e-02, -2.12935953e-03,  1.88466130e-01],
        [-3.85581279e-02, -1.32218701e-02, -8.99242351e-02],
        [-1.21766203e+00, -6.54239045e-01, -2.47202103e+00],
        [-2.94250915e-01, -1.84866340e-01, -1.07989685e+00]],

       [[ 3.55671272e-02,  4.92574734e-03, -4.35969844e-01],
        [ 1.69864185e-01,  5.82476981e-02,  3.96152711e-01],
        [ 2.09229241e+00,  1.12417022e+00,  4.24764075e+00],
        [ 3.55514512e-01,  2.23355862e-01,  1.30473342e+00]],

       [[-2.92687817e-02, -4.05347958e-03,  3.58766851e-01],
        [-1.42769284e-01, -4.89566542e-02, -3.32962708e-01],
        [-1.91977358e+00, -1.03147737e+00, -3.89740384e+00],
        [-4.33486363e-01, -2.72342526e-01, -1.59088906e+00]],

       [[-9.87358270e-02, -1.36740798e-02,  1.21027045e+00],
        [ 3.78286498e-01,  1.29717266e-01,  8.82229657e-01],
        [-2.72218677e+00, -1.46260689e+00, -5.52641275e+00],
        [-3.87074547e-01, -2.43183797e-01, -1.42055832e+00]],

       [[-4.31621908e-02, -5.97759963e-03,  5.29067571e-01],
        [-3.85581279e-02, -1.32218701e-02, -8.99242351e-02],
        [-1.51856698e+00, -8.15912615e-01, -3.08289938e+00],
        [-5.26309996e-01, -3.30659984e-01, -1.93155052e+00]],

       [[-4.31621908e-02, -5.97759963e-03,  5.29067571e-01],
        [-2.99086019e-01, -1.02558830e-01, -6.97520418e-01],
        [-2.12037688e+00, -1.13925975e+00, -4.30465606e+00],
        [-2.94250915e-01, -1.84866340e-01, -1.07989685e+00]],

       [[-4.77933271e-02, -6.61897298e-03,  5.85834478e-01],
        [ 6.56530285e-02,  2.25129140e-02,  1.53114238e-01],
        [-2.22067853e+00, -1.19315094e+00, -4.50828218e+00],
        [-5.26309996e-01, -3.30659984e-01, -1.93155052e+00]],

       [[ 4.48293999e-02,  6.20849404e-03, -5.49503657e-01],
        [-3.85581279e-02, -1.32218701e-02, -8.99242351e-02],
        [ 2.29289571e+00,  1.23195260e+00,  4.65489298e+00],
        [ 4.01926328e-01,  2.52514591e-01,  1.47506416e+00]],

       [[ 4.48293999e-02,  6.20849404e-03, -5.49503657e-01],
        [ 1.35474503e-02,  4.64552193e-03,  3.15950015e-02],
        [ 2.09229241e+00,  1.12417022e+00,  4.24764075e+00],
        [ 4.48338145e-01,  2.81673319e-01,  1.64539489e+00]]])